version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "7001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/share/nginx/html:ro

  adminer:
    image: adminer:latest
    ports:
      - "7002:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: thispass711
      MYSQL_USER: testuser
      MYSQL_PASSWORD: thispass711
      MYSQL_DATABASE: testdb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

